# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.


# https://mehmandarov.com/jekyll-content-on-time/#targetText=Setting%20the%20time%20zone%20in,%2C%20e.g.%2C%20Europe%2FOslo%20.
# set timezone
timezone: Europe/London

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#title: chizography
email: chisel@chizography.net
baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: chizcw
github_username:  chiselwright

# https://jekyllrb.com/docs/permalinks/
permalink: /blog/:year/:month/:day/:title:output_ext

socialmedia:
  facebook:       chiselwright
  github:         chiselwright
  instagram:      chizcw
  linkedin:       chiselwright
  twitter:        chizcw

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

feed:
  path: /blog/feed.xml

# Google Analytics
google_analytics: UA-25425412-1

# this chunk is based on:
# - https://brianm.me/posts/how-to-make-jekyll-site-blog

# seo
title: chizography
description: >- # this means to ignore newlines until "baseurl:"
    Chisel's personal website: a little bit of everything.
url: https://chizography.net

twitter:
  username: chizcw

facebook:
    app_id:       920275311667337
  publisher:
  admins:

logo: /assets/images/chisel_greybeard_and_games.jpg

social:
  name: Chisel Wright
  links:
    - https://github.com/chiselwright
    - https://facebook.com/chiselwright
    - https://twitter.com/chizcw
    - https://www.instagram.com/chizcw
    - https://www.last.fm/user/chiselwright
    - https://www.linkedin.com/in/chiselwright
    - https://steamcommunity.com/id/chizcw
    - https://www.youtube.com/c/ChiselWright

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/chisel_greybeard_and_games.jpg
